graph LR

CQ(Gather Requirements);
CS(Scope, Impact Analysis);
DR(Design Review);
TR(Technical Review);

C((Code));

U(Unit Tests);
ST(Smoke Tests);
IT(Integration Tests);
RT(Regression Tests);
PT(Performance Tests);

IM((Improve))

F(Formatter);
SA(Linter/Static Analysis);
CV(Code Coverage);
ML(Memory Leak);
MT(Multi-threading Check);

PR((PR));

Style(Style/Format);
CRI(Language Idioms);
CRD(Design Patterns);
CRA(Optimisation: Algo + DS);
VR(Verify Tests);
SCR(Security Code Review);

M((Merge));

subgraph Design
  CQ
  CS
  DR
  TR
end

subgraph Tests/CT
  U
  ST
  IT
  RT
  PT
end

subgraph Tools
  F
  SA
  CV
  ML
  MT
end

subgraph Code Review
  Style
  CRI
  CRD
  CRA
  VR
  SCR
end

CQ --> C;
CS --> C;
DR --> C;
TR --> C;

C --> U;
C --> ST;
C --> IT;
C --> RT;
C --> PT;

U --> IM;
ST --> IM;
IT --> IM;
RT --> IM;
PT --> IM;

IM --> F;
IM --> SA;
IM --> CV;
IM --> ML;
IM --> MT;

F --> PR;
SA --> PR;
CV --> PR;
ML --> PR;
MT --> PR;

PR --> Style;
PR --> CRI;
PR --> CRD;
PR --> CRA;
PR --> VR;
PR --> SCR;

Style --> M;
CRI --> M;
CRD --> M;
CRA --> M;
VR --> M;
SCR --> M;